#!/usr/bin/env bash

ANSI_FUERA_DEL_TABLERO='\x1b[00000000000000000m %c \x1b[0m\x00'
ANSI_DENTRO_DEL_TABLERO='\x1b[38;5;000;48;5;051m %c \x1b[0m\x00'
ANSI_DENTRO_DE_LA_FORTALEZA='\x1b[38;5;000;48;5;037m %c \x1b[0m\x00'

POSICIONES_FORTALEZA=("abajo" "arriba" "derecha" "izquierda")

for POSICION in "${POSICIONES_FORTALEZA[@]}"; do
    BUFFER_ARCHIVO=""
    for ((i=0; i<=6; i++)); do
        for ((j=0; j<=6; j++)); do
            if (( (i <= 1 && j <= 1) ||
                  (i >= 5 && j <= 1) ||
                  (i <= 1 && j >= 5) ||
                  (i >= 5 && j >= 5) )); then
                BUFFER_ARCHIVO+="$ANSI_FUERA_DEL_TABLERO"
            else
                if { [ "$POSICION" = "arriba" ]    && (( j >= 2 && j <= 4 && i >= 0 && i <= 2 )); } ||
                   { [ "$POSICION" = "abajo" ]     && (( j >= 2 && j <= 4 && i >= 4 && i <= 6 )); } ||
                   { [ "$POSICION" = "derecha" ]   && (( j >= 0 && j <= 2 && i >= 2 && i <= 4 )); } ||
                   { [ "$POSICION" = "izquierda" ] && (( j >= 4 && j <= 6 && i >= 2 && i <= 4 )); }; then
                    BUFFER_ARCHIVO+="$ANSI_DENTRO_DE_LA_FORTALEZA"
                else
                    BUFFER_ARCHIVO+="$ANSI_DENTRO_DEL_TABLERO"
                fi
            fi

        done
    done

    printf "%b" "$BUFFER_ARCHIVO" > "./static/tablero-${POSICION}.dat"
done
